### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [bjadams31/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by bjadams31** [comment]
Thanks Matt!  I clearly have a lot to learn to make the alignment do what I want it to do, but I have made it a little better now.  I added the "viewport meta tag"...was that the mobile tag you were referring to? I also removed some CSS that I had added for positioning the logo, slogan, and links trying to make it look better. But I think that was where I caused the mobile problems...not understanding what impact those actions had on the mobile view.

**Comment by Matt-Lepley** [comment]
Hey BJ.

The viewport meta tag is what I was referring to. Adding this tag allows users to be able to zoom and other things while on mobile devices. As far as the other css you had, I wasn't referring to that when suggesting to add the mobile tag. It is just good experience for new developers to know that there is a tag that allows for a better user experience on mobile devices.

Hope this helps!

**Comment by bjadams31** [comment]
Well I added the tag first and it still didn't fix it completely...so I just took it back to where I knew it was better.  Now that the videos are unlocked, and I have something to play with and apply it to, I will go back a revisit it to get more practice with the responsive design stuff!  Thanks for your input!

**Comment by Matt-Lepley** [comment]
Not a problem! Usually after an issue is completed or fixed (like this one) whoever fixed it closes the issue so others know that it is complete. Look forward to seeing your Nomster app! :+1:
